name: 添加公共服务器
description: 把自己的服务器添加到公共服务器列表
labels: [server]
title: "[Server] "
body:
  - type: input
    attributes:
      label: 联系方式
      description: Telegram、Github 账号等联系方式
    validations:
      required: true
  - type: input
    attributes:
      label: 域名
      description: 服务器域名
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: 支持地区
      description: 服务器支持解析的地区
      options:
        - 中国大陆
        - 港澳
        - 台湾
        - 东南亚
    validations:
      required: true
  - type: input
    attributes:
      label: 赞助地址
      description: 爱发电等
